name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-AMD64:

    runs-on: ubuntu-latest

    steps:
    -
      name: Get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_ACCOUNT }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: oak_ffc_4p_ros.dockerfile
        push: true
        tags: |
          hkustswarm/oak_ffc_img:${{ steps.date.outputs.today }}
          hkustswarm/oak_ffc_img:latest

  build-ARM64:

    runs-on: self-hosted

    steps:
    -
      name: Get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      shell: bash
      run: |
          docker build -t 192.168.1.132/hkustswarm/oak_ffc_img:${{ steps.date.outputs.today }} -t 192.168.1.132/hkustswarm/oak_ffc_img:latest -f oak_ffc_4p_ros.dockerfile .
          docker push 192.168.1.132/hkustswarm/oak_ffc_img:${{ steps.date.outputs.today }}
          docker push 192.168.1.132/hkustswarm/oak_ffc_img:latest